### ISSUE TITLE
how to pass variable to screen widget?

### ISSUE THREAD

**Issue by stoneLee81** [Bestfastfire/fragment_navigate#1]
can you explain how to ? thanks

**Comment by Bestfastfire** [comment]
> can you explain how to ? thanks

Hello, there is still no way to pass values ​​like as navigator.push method of the flutter but you can use external classes to make control and use a "get" on the new screen to retrieve the value.

Thanks for the feedback, a native way of the package will be implemented soon.

**Comment by stoneLee81** [comment]
got it, this plugin is useful for tablet interaction
